First commit
mag7ster/groebner-basis pull request #1
Opened 2024-01-17 20:08 UTC by mag7ster

First commit. Partitial complete:

Monom
Term
Polynom
Elementary reduce

Working with boost/rational

Not much have been done, becaouse understanding how to work with git, cmake, boost is more difficult for me than writing code

2024-02-05 14:05 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторялся с описанием ошибок. Если ошибка повторяется несколько раз, я ожидаю, что ты по аналогии поправишь все места.

В целом у тебя как-то стремно все наговнякано. Я постарался сделать комментарии на тему как и что поправить.

2024-02-05 14:05 UTC, DimaTrushin commented on .gitignore
> +.cache/
Кирпичи. Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-02-05 14:05 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 -Wall")
1) Никогда не выставляй напрямую компиляторазависимые флаги. Только внутри проверки на нужный компилятор.
2) Стандарт c++20 можно гарантировать на уровне cmake платформо независимым способом так
```cpp
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
```

2024-02-05 14:05 UTC, DimaTrushin commented on tostringhelper.h
> +std::string ToString(Field x);
Если Field тяжелые объекты, то у тебя лишнее копирование, при вызове этой функции. Аргумент будет копироваться внутрь функции.

2024-02-05 14:05 UTC, DimaTrushin commented on tostringhelper.h
> +std::string ToString(Field x);
Выглядит как функция нужная где-то внутри какого-то класса или другой функции.

2024-02-05 14:05 UTC, DimaTrushin commented on tostringhelper.cpp
> +template <>
Полное говно. Ты сделал инстанциацию шаблона только для одного конкретного класса Fraction. То есть шаблонную функцию toString у разрешено вызывать с любым параметром. При этом компилятор все спокойно прожует. Но упадет у тебя код при линковке. Вместо таких выкрутасов лучше сделай единственную функцию только для класса Fraction. И не мучай жопу. Не надо играть с линкером. Вообще это очень плохо имплементированная инстанциация шаблона.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +class Monom;
Плохо, что все классы в одном файле. Выдели порядки в один конкретный файл. Мономы в другой. Термы в третий. Полиномы в четвертый. Алгоритмы в пятый.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    friend class LexOrder;
Плохой дизайн. При добавлении любого порядка тебе надо будет не забыть добавить его сюда френдом. Убрать. У этих классов нет общего инварианта. Они не должны быть друзьями. У тебя недостаточный интерфейс для монома.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Monom(std::initializer_list<int> list);
Плохой тип int. Он не понятно что означает. Это что? Степень переменной или индекс переменной? лучше заведи using Degree = int;
Кроме того, если у тебя степень int, то надо обязательно проверять, что она не отрицательна (или даже положительна).

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Monom(std::initializer_list<int> list);
Вот как я, блядь, должен искать имплементацию этого метода? Сканить весь файл со сборной солянкой по мотивам проекта?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +protected:
Плохая идея делать защищенные данные. Особенно если на них у тебя есть инвариант. Тогда производный класс может его нарушить. Лучше данные сделать приватными, и предоставить нужный публичный и защищенный интерфейс для взаимодействия с данными с сохранением инвариантов.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.cpp
> +    }
Плохой подход.
1) Ты аллоцируешь слишком много памяти зарание.
2) Ты не проверяешь корректность данных. У тебя может list содержать отрицательные значения.
Лучше выдели метод, который чистит и подготавливает данные. И потом уже
```cpp
Monom::Monom(std::initializer_list<int> degrees) : degs_(createDegrees(degrees)) {}

std::vector<Degree> createDegrees(std::initializer_list<int> degrees) {
  // проверка, что все степени не отрицательные
  // аллокация только нужного размера вектора и заполнение его.
  // вернуть вектор
}
```

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Monom(std::initializer_list<int> list);
Плохое имя переменной. Что такое list? Что пользователь передает? degrees будет куда проще читать.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    std::vector<int> degs_;
почему сокращаешь названия?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    bool operator()(const Monom &a, const Monom &b);
оператор должен быть const

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.cpp
> +bool LexOrder::operator()(const Monom &a, const Monom &b) {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.cpp
> +    for (size_t i = 0; i < std::min(a.degs_.size(), b.degs_.size()); ++i) {
Есть std::lexicographical_compare, только вызови его правильно, умоляю.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Term(std::pair<Field, std::initializer_list<int>> term)
Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры. 

Я вообще не понимаю, что мешает тебе тут просто принять два параметра. Зачем усложнять и срать в бутылку?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    std::string ToString() {
1) Во-первых, не понятно почему метод не const.
2) Во-вторых, вместо этого лучше перегрузить operator<< для вывода в произвольный поток.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +                            const groebner_basis::Term<T> &divisor);
Тут все так плохо, что я даже не знаю с чего начать...
1) С хуя метод шаблонный? У тебя тип терма уже известен.
2) Какого хрена namespace явно прописан????? Убрать.
3) френды у шаблонов всегда определяются inline
4) Плохо назван метод, вот смотри
```cpp
Term m1, m2;
bool f = IsDivisible(m1, m2);
```
Вопрос, проверка делимости кого на кого была сделана?
5) Для терма проверка на делимость не имеет смысла. Потому что у терма есть коэффициент, который не должен влиять на делимость (кроме вырожденного случая с нулем). Потому этот метод должен быть у монома.
6) Лучше сделать метод класса
```cpp
class Monomial {
public:
  bool isDivisibleBy(const Monomial& other) const;
};
```

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Polynom(std::initializer_list<std::pair<Field, std::initializer_list<int>>> list) {
Убрать std::pair. Заменить на нормальную структуру.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +            data_.emplace_back(*it);
У тебя поддерживается инвариант, что последний в векторе терм с ненулевым коэффициентом? Если да, то тут ты его только что сломал.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    std::string ToString() {
убрать и сделать operator<<

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    Term<Field> GetFirstTerm() {
FirstTerm не имеет смысла без порядка. Потому такой метод должен получать в качестве аргумента порядок. Первый же терм в векторе не имеет никакого смысла.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    friend std::optional<Term<T>> FindDivisibleTerm(const Polynom<T> &f, const Term<T> &t);
блять

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    friend std::optional<Polynom<T>> ElementaryReduction(Polynom<T> f, Polynom<T> g, Functor order);
Какого хуя все передается by value?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    std::vector<Term<Field>> data_;
В каком порядке хранятся термы? Хранятся ли термы с нулевыми коэффициентами?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +
Я ожидаю у мономов возможность перемножать. Возможность проверки на делимость. Возможность делить. Возможность прочитать степень переменной по индексу (если переменная не хранится, то должен возвращаться 0, а не падение программы).

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +
Я ожидаю возможность получать доступ к коэффициенту терма и к моному, чтобы их читать и/или менять.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +
Ожидаю видеть операции сложения, вычитания, умножения многочленов между собой. Прибавление и вычитание терма к многочлену.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    for (size_t i = 0; i < std::min(term.degs_.size(), divisor.degs_.size()); ++i) {
Когда пишешь term.degs_.size() -- это ошибка уровня доступа. Никогда не должно быть обращение к кишкам кишков. Ты делаешь что-то не то.

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    for (auto &t : f.data_) {
какого хуя не const auto&?

2024-02-05 14:05 UTC, DimaTrushin commented on groebner_basis.h
> +    std::sort(g.data_.begin(), g.data_.end(), order);
Дороговато. У тебя подобный метод будет зваться кучу раз во время сложных редукций. Лучше иметь два метода элементарной редукции, один для внутреннего пользования приватный, который предполагает отсортированность. И один для внешнего использования, который сам сортирует и потом уже зовет что надо.
Только если будешь сортировать, то копировать может быть дорого. Может быть лучше создать дополнительный прокси объект vector_view, который будет сортироваться и не будет копировать лишний раз данные. Но это уже надо тестить.

2024-02-05 19:54 UTC, mag7ster commented on tostringhelper.cpp
> +template <>
Я сейчас вообще этот хелпер снести хочу, он мне самому не нравится. хочу просто по-человечески определить operator<< чтобы выводить

2024-03-30 18:07 UTC, DimaTrushin requested changes
накидал еще хуев.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +using Degree = unsigned int;
Не делай глобальные юзинги в случайных местах. Либо заведи единый хедер, в который положи общие юзинги, либо лучше заведи этот юзинг внутри класса Monom, где ему и место.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +static std::vector<Degree> CreateDegrees(const std::initializer_list<Degree>& degrees_list) {
1) Спрячь эту функцию в Monom в приватную часть.
2) Нет смысла в хедере делать static функцию. Дело в том, что static внутри класса и внутри namespace имеет разное поведение. Потому спрячь эту гадость. Ее никто не должен видеть, это деталь имплементации.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    for (const auto& elem : degrees_list) {
у тебя elem типа unsigned int, не принимай его по ссылке. Напиши auto

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    for (const auto& elem : degrees_list) {
Я правильно понимаю, что ты этой хуйней просто искал позицию последнего ненулевого элемента? Есть же std::find_end
https://en.cppreference.com/w/cpp/algorithm/find_end

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    }
это std::copy

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        : degrees_(CreateDegrees(degrees_list)) {
Лучше назови метод более подходящим образом вроде TrimTrailingZeros

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        return degrees_ != other.degrees_;
лучше написать return !(*this == other); и не дублировать имплементацию.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    size_t CountDegrees() const {
Плохое название функции. Это индекс переменной которая следующая за последней присутствующей в мономе. Надо нормальное название для метода. Вот что такое 
```cpp
Monom m;
m.CountDegrees();
```
Вот что этот метод возвращает? Он что считает? Какие степени? Выглядит как сумма степеней.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        }
Это называется std::any_of
https://en.cppreference.com/w/cpp/algorithm/all_any_none_of

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    }
Самый бессмысленный и жестокий конструктор, который я когда-либо видел. В таком конструкторе нет смысла. Сделай так
```cpp
explicit Monom(std::vector<Degree>&& vec) : degrees_(std::move(vec)) {
}
```
Иначе ты зря копируешь вектор. Раз это приватный конструктор, то ты будешь его использовать внутри своих методов. Значи ты можешь себе позволить воровать из объектов все кишки.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        return Monom(newdegrees);
```cpp
return Monom(std::move(newdegrees));
```
Иначе у тебя лишний раз копируется newdegrees

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    Monom operator/(const Monom& other) const {
Что помешало сделать метод inplace через оператор operator/=?

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        }
Это опять std::find_end

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +    Monom operator*(const Monom& other) const {
Тот же вопрос про inplace версию.

2024-03-30 18:07 UTC, DimaTrushin commented on src/monom.h
> +        return Monom(newdegrees);
std::move

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +struct NotConstructedTerm {
Это что за хуйня еще?

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +static std::vector<Term<Field>> ReduceSimilarInVectorForPolynom(std::vector<Term<Field>> data) {
Спрячь все вспомогательные функции внутрь класса, где они вспомогательные.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +static std::vector<Term<Field>> ReduceSimilarInVectorForPolynom(std::vector<Term<Field>> data) {
Что значит это название?

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +static std::vector<Term<Field>> CreateVectorFromInitializerList(
Плохое название, потому что вектор и так можно создать из initializer_list. Назови как-нибудь более специфично. CreateFromRawData или что-то в этом духе.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +    return ReduceSimilarInVectorForPolynom<Field>(data);
1) А это что за хуйня?
2) Ты делаешь тут лишнее копирование, потому что принимаешь контейнер по значению. Надо писать
```cpp
return ReduceSimilarInVectorForPolynom<Field>(std::move(data));
```
Чтобы избежать такого, лучше контейнер принимать по rvalue reference.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +    Polynom(const Term<Field>& term) : data_(ReduceSimilarInVectorForPolynom<Field>({term})) {
У меня есть подозрение, что в этом синтаксисе у тебя term будет скопирован дважды.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +        while ((it + 1) != data.end() && IsDeegreesEqual(*it, *(it + 1))) {
Что делает функция IsDeegreesEqual? Обрати внимание на опечатку Deeg вместо Deg.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +        while ((it + 1) != data.end() && IsDeegreesEqual(*it, *(it + 1))) {
Какого хуя тут вообще происходит? Это что std::remove_if?
https://en.cppreference.com/w/cpp/algorithm/remove

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +    const Term<Field>& GetFirstTerm() const {
Плохо, лучше скажи это largest или smallest?

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +
Перед вставкой в вектор лучше сделать reserve.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +        return (*this) + (-other);
Из твоих имплементаций, это супер не эффективно.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +
Надо добавить += и прочие inplace операции.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +}
Это высота ебанистики. Ты взял все из худших миров. Ты сделал конструктор не explicit, чтобы была конвертация типов и не сделал правильные бинарные операторы. Надо внутри класса объявить оператор
```cpp
friend Polynom operator*(const Polynom& first, const Polynom& second) {
  // Implementation
}
```
И тогда это будет глобальный НЕ шаблонный оператор умножения, который будет допускать конвертацию типов. Это ровно то, что я говорил на лекциях.

2024-03-30 18:07 UTC, DimaTrushin commented on src/polynom.h
> +    return -(p - t);
пиздец заоптимизировал

2024-03-30 18:07 UTC, DimaTrushin commented on src/term.h
> +    Term<Field> operator/(const Term<Field>& other) const {
Если есть не безопасные операции, то должен быть метод проверки, что их можно выполнить.

2024-03-30 18:07 UTC, DimaTrushin commented on src/term.h
> +}
Что мешало сделать метод monom(), который возвращает const Monom& и пользоваться им для сравнения мономов? Аналогично бы хорошо иметь метод для доступа к коэффициенту. И для изменения их тоже бы немешало иметь методы.

2024-03-30 18:07 UTC, DimaTrushin commented on src/groebner_basis.h
> +std::optional<Polynom<Field, Order>> ElementaryReduction(const Polynom<Field, Order> &f,
При этом ты не контролируешь моном, который редуцируешь?

2024-03-30 18:07 UTC, DimaTrushin commented on src/groebner_basis.h
> +    if (res == std::nullopt) {
можно просто if(!res)

2024-03-30 18:07 UTC, DimaTrushin commented on src/groebner_basis.h
> +    Term<Field> divisible_term = res.value();
Вот тут лишняя копия этого терма происходит. Лучше ссылку создай на него.

2024-03-30 18:43 UTC, mag7ster commented on src/term.h
> +    Term<Field> operator/(const Term<Field>& other) const {
Но у меня ведь есть проверка в имплементации деления монома

2024-05-10 12:30 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Есть какие-то мелочи, которые хочется поправить. Меня смущает, что ты все в хедерах поместил и местами словил ODR Violation. Будь к этому внимательнее.

В остальном есть какие-то мелкие замечания, но в основном одинаковые, потому я особено не повторялся.

2024-05-10 12:30 UTC, DimaTrushin commented on CMakeLists.txt
> +add_executable(main ${SOURCE_EXE})
Пустая строка

2024-05-10 12:30 UTC, DimaTrushin commented on src/main.cpp
> +    file.close();
Не закрывай файловые потоки руками. Они закрываются деструкторами.

2024-05-10 12:30 UTC, DimaTrushin commented on src/main.cpp
> +
Если у тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Test.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
Вообще main не должна ничего делать, она все делегирует другим. Она занимается оркестровкой всей деятельности. Всю работу делает другой кусок кода.

2024-05-10 12:30 UTC, DimaTrushin commented on src/main.cpp
> +void Check(gb::PolynomialsSet<Fraction, gb::GrevLexOrder>& find,
Если определяешь что-то в cpp файле, то оборачивай в anonymous namespace.

2024-05-10 12:30 UTC, DimaTrushin commented on src/main.cpp
> +// void PrintCyclic(size_t n) {
Не оставляй закомментированный код. Храни его в других ветках.

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +    Monom() : Monom(std::vector<Degree>()) {
Какого хрена. Это просто
```cpp
Monom() = default;
```

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +    std::shared_ptr<const std::vector<Degree>> degrees_;
Что блять?
Сделай тогда хотя бы
```cpp
std::shared_ptr<const std::vector<Degree>> degrees_ = std::make_shared<const std::vector<Degree>>();
```

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +    Monom() : Monom(std::vector<Degree>()) {
Почему имплементация НЕ в cpp файле?

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +    Degree operator[](size_t index) const {
Плохо использоваь оператор, потому что вообще говоря не понято, что такое m[3], а если пишешь m.deg(3), то это более читаемее.

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +    size_t CountSignificantDegrees() const {
Эта функция врет своим названием. Это максимальный индекс переменной, которая присутствует в мономе. То есть что-то вроде indexOfLastVariable или highestVariableIndex Или что-то в этом духе.

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +        return std::mismatch(divisor.begin(), divisor.end(), this->begin(), this->end(),
не используй this для доступа к метода, используй просто begin и end.

2024-05-10 12:30 UTC, DimaTrushin commented on src/monom.h
> +Monom BuildMonomFromVectorDegrees(const std::vector<Monom::Degree>& vector_degrees) {
ЭТО ODR Violation. Если определяешь функцию в хедере вне класса, то надо обязательно писать inline.

2024-05-10 12:30 UTC, DimaTrushin commented on src/functions.h
> +Monom LCM(const Monom& m1, const Monom& m2) {
Это ODR Violation. Либо inline, либо в cpp перенеси имплементацию нешаблонного метода.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    std::optional<Polynom> Reduce(const Polynom &f) const {
В целом это не лучший дизайн помещать в контейнер содержательные алгоритмы. Суть контейнера в том, чтобы поддерживать инварианты контейнера, а содержатаельные методы должны быть отдельно.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +        Builder&& AddTerm(const Field& coef,
Что это за хуйня? Зачем возвращать rvalue reference? Надо возвращать обычную ссылку.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +        friend class Polynom;
Зачем полиному быть другом у строителя? Зачем вообще полиному знать про строителя и его методы. Я бы понял обратное, если бы строитель был другом у полинома, но в эту сторону -- это ошибка дизайна.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +
А где метод get() чтобы вытащить из билдера полином?

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +        std::vector<Term>&& GetMovedRawData() {
Лучше назови ExtractData. Тогда будет понятно, что ты вынимаешь оттуда данные.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +        : Polynom(OrderAndReduceVector(std::move(builder.GetMovedRawData()))) {
лишний std::move

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +    std::optional<Polynom> ElementaryReduceBy(const Polynom& g) const {
Хреново, что у тебя методы редукции раскиданы между полиномами и множеством полиномов. Лучше методы сложить в отдельный объект или отедльное пространство имен или уж просто в пространство имен проекта в виде глобальных функций.

Еще одно замечание. У тебя разнве интерфейсы. У метода с множествами ты возвращаешь число итераций и действуешь inplace, а тут ты строишь новый многочлен. Этого не видно, потому что методы размазаны по разным классам.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +    bool IsCorrect() {
Если метод используется внутри assert-а, то не используй внутри этого метода assert-ы. Потому что ты рискуешь войти в бесконечную рекурсию ибо можешь незаметно через assert-ы позвать тот же самый метод.

2024-05-10 12:30 UTC, DimaTrushin commented on src/polynom.h
> +    class Builder {
Если ты хочешь воспользоваться во всю силу shared_ptr на константные мономы, тебе надо иметь глобальный builder, который помнит все мономы, которые только встречалиь и во время любой операции переиспользует нужный моном. Но я даже не знаю, как ты это будешь писать. Вообще все это выглядит так, что не надо было этим заниматься.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +            count_passes += 1;
а что стало с операцией ++?

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +        bool success = false;
как же галимо выглядит флаг особенно булев. Более чем уверен, что его можно убрать.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    auto begin() const {  // NOLINT
Зачем тут auto? Что мешало использовать конкретный тип итератора? Тем более, что ты для его даже using сделал.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    PolynomialsSet() {
= defaul;

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    PolynomialsSet(const std::initializer_list<Polynom> &poly_list) : data_(poly_list) {
НИКОГДА НЕ принимай initializer_list по константной ссылке, всегда принимай его по значению. Он уже внури состоит из одного указателя на константные данные. Потому это просто лишний джамп в памяти. И надо понимать, что из initializer_list не возможно мувнуть данные, потому ты их всегда копируешь.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    PolynomialsSet(const std::initializer_list<Polynom> &poly_list) : data_(poly_list) {
Еще вопрос, ты разрешаешь повторяться многочленам в множестве? Если нет, то у тебя нельзя просто так конструировать множество о происхольному инициализатору. Надо добавить чистку данных.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +    void Add(const Polynom &poly) {
Добавь еще метод с Polynom&& и мувом данных внутрь. Это может понадобится.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +        auto it = this->begin();
убери все лишние this

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +
убери лишние вертикальные пробелы.

2024-05-10 12:30 UTC, DimaTrushin commented on src/groebner_basis.h
> +        AutoReduction();
Нарушение уровня абстракции. У тебя выше низкоуровневый код в виде сырых циклов, а тут идет вызов сложной функции. Значит и выше шаги должны быть завернуты в более высокоуровневые вызовы. Код должен быть на одном уровне абстракции.

2024-05-12 13:01 UTC, mag7ster commented on src/monom.h
> +    Degree operator[](size_t index) const {
Я не знаю, как сделать это по другому. Если я буду возвращать const vector&, то не смогу заифать, чтобы возвращался 0 когда степень больше чем есть в векторе

2024-05-12 13:14 UTC, mag7ster commented on src/groebner_basis.h
> +            count_passes += 1;
Мне она кажется некрасивой когда стоит отдельно на одной строчке

2024-05-12 13:16 UTC, mag7ster commented on src/groebner_basis.h
> +    PolynomialsSet(const std::initializer_list<Polynom> &poly_list) : data_(poly_list) {
Разрешаю

2024-05-12 15:59 UTC, DimaTrushin requested changes
Добавил мелкие замечания.

2024-05-12 15:59 UTC, DimaTrushin commented on src/monom.h
> +    Degree operator[](size_t index) const {
Я не про это. Я про то, что вместо оператора лучше функцию с говорящим именем. Вектор вообще не надо возвращать конечно.

2024-05-12 15:59 UTC, DimaTrushin commented on src/monom.h
> +        return degrees_->at(index);
Блять. А нахуя at? Он же вообще бросает исключения и потому его хуже оптимизирует компилятор.

2024-05-12 15:59 UTC, DimaTrushin commented on src/tests.cpp
> +void Check(gb::PolynomialsSet<ModInt>& find, gb::PolynomialsSet<ModInt>& ans) {
anonymous namespace

2024-05-12 15:59 UTC, DimaTrushin commented on src/types.h
> +        return (*this) = (*this) + other;
Почему inplace оператции определяются через не inplace операции?

2024-05-12 15:59 UTC, DimaTrushin commented on src/types.h
> +    Modulus() : value_(0) {
Почему не Modulus() = default; и дефолтное значение у поля?

2024-05-12 15:59 UTC, DimaTrushin commented on src/types.h
> +        }
Почему это НЕ часть кода при инициализации? Перенести в список инициализации через ? оператор.

2024-05-12 18:51 UTC, mag7ster commented on src/types.h
> +        return (*this) = (*this) + other;
По-моему так брать модуль удобнее

2024-05-12 19:01 UTC, mag7ster commented on src/types.h
> +        }
Тернарный оператор по-моему жутко нечитаемый

2024-05-16 13:02 UTC, merged